import six
import tensorflow as tf
import tensorflow_datasets as tfds
from load_data_tensorflow import CUSTOMER_ID
from load_data_tensorflow import __DEFAULT_PAGE_SIZE
from load_data_tensorflow import query
from load_data_tensorflow import csv
from google.ads.google_ads.client import GoogleAdsClient
from google.ads.google_ads.errors import GoogleAdsException 

def main():
    """ This function calls the query function to get a list of data and column names. 
    Then it calls the csv helper method which in turn makes a dataframe and then it converts
    it into a CSV. The last step is to use this CSV generated by the helper method to load
    data directly into tensorflow.
    """
    client = GoogleAdsClient.load_from_storage("./google-ads.yaml")
    results = query.get_keywords_and_impressions(client, six.text_type(CUSTOMER_ID),
                                       __DEFAULT_PAGE_SIZE)
    csv_repr = csv.csv_creator(results)
    df  = csv_repr.get_data_frame()
    csv_repr.save_to_csv('results.csv')
    #Loads data into tensorflow with the help of a csv file. Batch_size and epochs are kept low for demonstration purposes. 
    dataset = tf.data.experimental.make_csv_dataset(
          'results.csv',
          batch_size=12, 
          na_value="?",
          num_epochs=1,
          ignore_errors=True)
    res = next(iter(dataset))
    print(res)
